# SPDX-FileCopyrightText: 2026-present LavLab <domurphy@mcw.edu>
#
# SPDX-License-Identifier: MIT
"""Generate a downsampled image purely over OMERO's tile API."""

from __future__ import annotations

import asyncio
import logging
from collections.abc import AsyncIterator, Sequence
from math import ceil

import numpy as np
import pyvips as pv

from lavlab.omero_asyncio import AsyncSession

log = logging.getLogger(__name__)

PARALLEL_STORE_COUNT = 4

_DEFAULT_TILE_SIZE = (1024, 1024)

_SIZE_WARN_BYTES = 4 * 1024**3

Tile = tuple[int, int, int, tuple[int, int, int, int]]


class LargeReconError(Exception):
    """Raised when a large recon can't be fetched or generated by any tier."""


def downsampled_xy(image, downsample: int) -> tuple[int, int]:
    """Target ``(width, height)`` for *image* at *downsample*.

    :param image: An OMERO ``ImageWrapper``.
    :param downsample: Downsample factor.
    :return: ``(width, height)``, each at least 1.
    """
    target_w = max(1, round(image.getSizeX() / downsample))
    target_h = max(1, round(image.getSizeY() / downsample))
    return target_w, target_h


def closest_resolution_level(rps, target_xy: tuple[int, int]):
    """Pick the smallest pyramid level still >= *target_xy*, and park *rps* on it.

    :param rps: An already-initialised RawPixelsStore (``setPixelsId``
        already called).
    :param target_xy: ``(width, height)`` to approximate.
    :return: ``(level, (level_size_x, level_size_y), (tile_w, tile_h))``.
    :raises LargeReconError: if the computed level is out of range.

    """
    n = rps.getResolutionLevels()
    descs = rps.getResolutionDescriptions()  # index 0 == full res, descending
    target_w, target_h = target_xy

    chosen_desc_idx = 0
    for i, d in enumerate(descs[1:], start=1):
        if d.sizeX >= target_w and d.sizeY >= target_h:
            chosen_desc_idx = i
        else:
            break

    level = n - 1 - chosen_desc_idx
    if not (0 <= level < n):
        raise LargeReconError(
            f"computed resolution level {level} is out of range 0..{n - 1}"
        )

    rps.setResolutionLevel(level)
    tile_w, tile_h = rps.getTileSize()
    if not tile_w or not tile_h:
        tile_w, tile_h = _DEFAULT_TILE_SIZE

    level_w, level_h = descs[chosen_desc_idx].sizeX, descs[chosen_desc_idx].sizeY
    tile_w = min(tile_w, level_w)
    tile_h = min(tile_h, level_h)

    return level, (level_w, level_h), (tile_w, tile_h)


def create_tile_list_2d(
    z: int, c: int, t: int, size_x: int, size_y: int, tile_size: tuple[int, int]
) -> list[Tile]:
    """Build a tile-coordinate list for one (z, c, t) plane, clamped at the edges.

    :param size_x: Width of the plane being tiled (the *chosen resolution
        level's* width, never full-res).
    :param size_y: Height of the plane being tiled (same caveat).
    :param tile_size: Nominal ``(width, height)`` per tile.
    :return: List of ``(z, c, t, (x, y, w, h))``.
    """
    tile_list: list[Tile] = []
    base_width, base_height = tile_size
    for y in range(0, size_y, base_height):
        width, height = base_width, base_height
        if size_y - y < height:
            height = size_y - y
        for x in range(0, size_x, base_width):
            if size_x - x < width:
                width = size_x - x
            tile_list.append((z, c, t, (x, y, width, height)))
    return tile_list


def create_full_tile_list(
    z_indexes: Sequence[int],
    channels: Sequence[int],
    timepoints: Sequence[int],
    width: int,
    height: int,
    tile_size: tuple[int, int],
) -> list[Tile]:
    """Concatenate :func:`create_tile_list_2d` across every (z, c, t) combination."""
    tile_list: list[Tile] = []
    for z in z_indexes:
        for c in channels:
            for t in timepoints:
                tile_list.extend(create_tile_list_2d(z, c, t, width, height, tile_size))
    return tile_list


def _chunkify(lst: Sequence, n: int) -> list[list]:
    """Split *lst* into *n* chunks (some may be empty if ``len(lst) < n``)."""
    if not lst:
        return []
    size = ceil(len(lst) / n)
    return [list(lst[i * size : i * size + size]) for i in range(n)]


_DONE = object()


def merge_async_iters(*aiters):
    """Merge async generators via an asyncio.Queue."""
    queue: asyncio.Queue = asyncio.Queue(1)
    cancelling = False

    async def drain(source):
        try:
            async for item in source:
                await queue.put((False, item))
        except Exception as e:
            if not cancelling:
                await queue.put((True, e))
        finally:
            await queue.put((None, _DONE))

    async def merged():
        remaining = len(aiters)
        try:
            while remaining:
                raised, next_item = await queue.get()
                if next_item is _DONE:
                    remaining -= 1
                    continue
                if raised:
                    cancel_tasks()
                    raise next_item
                yield next_item
        finally:
            cancel_tasks()

    def cancel_tasks():
        nonlocal cancelling
        cancelling = True
        for t in tasks:
            t.cancel()

    tasks = [asyncio.create_task(drain(source)) for source in aiters]
    return merged()


async def _fetch_tile_chunk(
    session,
    pixels_id: int,
    tiles: Sequence[Tile],
    level: int | None,
    bypass: bool = True,
) -> AsyncIterator[tuple[np.ndarray, Tile]]:
    """Fetch one chunk of tiles from a single async RawPixelsStore."""
    rps = await session.createRawPixelsStore()
    closed = False
    try:
        await rps.setPixelsId(pixels_id, bypass)
        lvl = level
        if lvl is None:
            lvl = (await rps.getResolutionLevels()) - 1
        await rps.setResolutionLevel(lvl)  # exactly once, before any getTile
        for z, c, t, (x, y, w, h) in tiles:
            buf = await rps.getTile(z, c, t, x, y, w, h)
            arr = np.frombuffer(buf, dtype=np.uint8).reshape(h, w)
            yield arr, (z, c, t, (x, y, w, h))
        await rps.close()
        closed = True
    finally:
        if not closed:
            try:
                await rps.close()
            except Exception:
                log.debug("rps close after abort failed", exc_info=True)


def _get_session_factory(conn):
    sf = getattr(conn.c, "sf", None)
    if sf is None and hasattr(conn.c, "getSession"):
        sf = conn.c.getSession()
    if sf is None:
        raise LargeReconError(
            "OMERO session factory unavailable; is the connection live?"
        )
    return sf


def _switch_group_before_stateful_service(conn, image) -> None:
    """Switch the session's security context before opening any stateful service."""
    group_id = image.details.group.id.val
    if hasattr(conn, "setGroupForSession"):
        try:
            conn.setGroupForSession(group_id)
            return
        except Exception:
            log.debug(
                "setGroupForSession failed, falling back to raw setSecurityContext",
                exc_info=True,
            )
    _get_session_factory(conn).setSecurityContext(image.details.group)


async def _gather_tiles(
    conn,
    pixels_id: int,
    tiles: list[Tile],
    level: int,
    arr: np.ndarray,
    store_count: int,
) -> None:
    session = AsyncSession(_get_session_factory(conn))
    chunks = [chunk for chunk in _chunkify(tiles, store_count) if chunk]
    jobs = [
        _fetch_tile_chunk(session, pixels_id, chunk, level, True) for chunk in chunks
    ]

    total = len(tiles)
    # Report roughly 20 updates regardless of total tile count, so a
    # multi-minute fetch isn't silent -- this class of hang has already cost
    # real debugging time once (see merge_async_iters' docstring).
    log_every = max(1, total // 20)
    fetched = 0
    log.info("Fetching %d tiles across %d parallel store(s)...", total, len(chunks))

    async for tile, (_z, c, _t, (x, y, w, h)) in merge_async_iters(*jobs):
        arr[y : y + h, x : x + w, c] = tile
        fetched += 1
        if fetched % log_every == 0 or fetched == total:
            log.info(
                "Fetched %d/%d tiles (%.0f%%).", fetched, total, 100 * fetched / total
            )


def generate_over_network(
    conn, image, downsample: int, store_count: int = PARALLEL_STORE_COUNT
) -> pv.Image:
    """Build a downsampled recon of *image* purely over the OMERO tile API.

    :raises LargeReconError: if *image* isn't uint8, or generation is
        attempted from within an already-running event loop.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        pass
    else:
        raise LargeReconError(
            "generate_over_network() cannot be called from within a running event loop."
        )

    pixels = image.getPrimaryPixels()
    pixel_type = pixels.getPixelsType().getValue()
    if pixel_type != "uint8":
        raise LargeReconError(
            f"image {image.getId()} has pixel type '{pixel_type}'; network "
            "large-recon generation only supports uint8 (RGB) images."
        )
    if image.getSizeZ() > 1 or image.getSizeT() > 1:
        log.warning(
            "Image %d has multiple Z/T planes; only z=0, t=0 will be fetched.",
            image.getId(),
        )

    target_w, target_h = downsampled_xy(image, downsample)

    _switch_group_before_stateful_service(conn, image)

    pixels_id = pixels.getId()
    rps = conn.createRawPixelsStore()
    try:
        rps.setPixelsId(pixels_id, True)
        level, (level_w, level_h), tile_size = closest_resolution_level(
            rps, (target_w, target_h)
        )
    finally:
        rps.close()

    channels = list(range(image.getSizeC()))
    tiles = create_full_tile_list([0], channels, [0], level_w, level_h, tile_size)

    nbytes = level_w * level_h * len(channels)
    if nbytes > _SIZE_WARN_BYTES:
        log.warning(
            "Image %d: allocating a %.1f GB array for tile assembly.",
            image.getId(),
            nbytes / 1024**3,
        )

    arr = np.zeros((level_h, level_w, len(channels)), dtype=np.uint8)

    asyncio.run(_gather_tiles(conn, pixels_id, tiles, level, arr, store_count))

    if arr.shape[2] == 1:
        arr = arr[:, :, 0]

    img = pv.Image.new_from_array(arr)
    del arr
    if (img.width, img.height) != (target_w, target_h):
        img = img.resize(target_w / img.width, vscale=target_h / img.height)
    return img
